Fixed the deprecated --old-chroot option issue
Running latest mock w/ --old-chroot option now
causes it to fail on the latest version of mock w/:
ERROR: Option --old-chroot has been deprecated.
Use --isolation=simple instead.

This patch updates the mock_runner.sh to use
the suggested option instead in case it's available in mock.

Change-Id: I91b0548c8b0e55e79080a8aa7c5a901504c90808
Signed-off-by: Lev Veyde <lveyde@redhat.com>