beaker: fix for loop in job submission and host selection.
Also checking if a check-install task was removed.

Exception: <Fault 1: "<class 'bkr.common.bexceptions.BX'>:Invalid task(s): /distribution/check-install">

Signed-off-by: Ehud Yonasi <eyonasi@redhat.com>
Change-Id: I35b9b59c195194183232c2e8d4735973170ef6cd