ovirt-engine_create-rpms: add JPP devel el6 repo
Add JPP devel repo for el6 build.
Solves:

DEBUG util.py:378:  Error: Package: plexus-cipher-1.7-3.jpp6.noarch
(jpackage-6.0-generic)
DEBUG util.py:378:             Requires: sisu2
DEBUG util.py:378:  Error: Package:
maven-project-info-reports-plugin-2.1.2-1.jpp6.noarch
(jpackage-6.0-generic)
DEBUG util.py:378:             Requires: maven-doxia-tools
DEBUG util.py:378:  Error: Package: maven3-3.0.3-8.jpp6.noarch
(jpackage-6.0-generic)
DEBUG util.py:378:             Requires: sisu2 >= 2.1.1-2
DEBUG util.py:378:  Error: Package: aether-1.13.1-2.jpp6.noarch
(jpackage-6.0-generic)
DEBUG util.py:378:             Requires: ops4j-pax-swissbox
DEBUG util.py:378:  Error: Package:
maven-remote-resources-plugin-1.2.1-2.jpp6.noarch (jpackage-6.0-generic)
DEBUG util.py:378:             Requires: maven-shared-artifact-resolver
DEBUG util.py:378:  Error: Package:
maven-checkstyle-plugin-2.5-2.jpp6.noarch (jpackage-6.0-generic)
DEBUG util.py:378:             Requires: maven-doxia-tools

Change-Id: I66d09c0c411cccbc045db6b635d912e09e7da2e3
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>